/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package manager;

import java.awt.Color;


/**
 *
 * @author VND
 */
public class GUIAdministrator extends javax.swing.JFrame {

    /**
     * Creates new form GUIAdministrator
     */
    public GUIAdministrator() {
        initComponents();
    }
    
    static public void onCreate(){
        txtUser.setText("Vi Ngọc Đông (Quản trị viên)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tvQuanLy = new javax.swing.JLabel();
        tvQLYC = new javax.swing.JLabel();
        tvYCDK = new javax.swing.JLabel();
        tvYCTD = new javax.swing.JLabel();
        tvQLTK = new javax.swing.JLabel();
        tvBaoTri = new javax.swing.JLabel();
        tvBTL = new javax.swing.JLabel();
        tvBTP = new javax.swing.JLabel();
        tvLS = new javax.swing.JLabel();
        tvLogout = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taYCDK = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chức năng dành cho quản trị viên");
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN TRỊ HỆ THỐNG ĐĂNG KÝ LỊCH THỰC HÀNH");

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtUser.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtUser.setText("ten");

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tvQuanLy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tvQuanLy.setText("Quản lý");
        tvQuanLy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvQuanLyMouseClicked(evt);
            }
        });

        tvQLYC.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tvQLYC.setText("Quản lý yêu cầu");
        tvQLYC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvQLYCMouseClicked(evt);
            }
        });

        tvYCDK.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tvYCDK.setText("Yêu cầu đăng ký lịch thực hành");
        tvYCDK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvYCDKMouseClicked(evt);
            }
        });

        tvYCTD.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tvYCTD.setText("Yêu cầu thay đổi lịch thực hành");
        tvYCTD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvYCTDMouseClicked(evt);
            }
        });

        tvQLTK.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tvQLTK.setText("Quản lý tài khoản");
        tvQLTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvQLTKMouseClicked(evt);
            }
        });

        tvBaoTri.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tvBaoTri.setText("Bảo trì");
        tvBaoTri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvBaoTriMouseClicked(evt);
            }
        });

        tvBTL.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tvBTL.setText("Bảo trì lịch thực hành");
        tvBTL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvBTLMouseClicked(evt);
            }
        });

        tvBTP.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tvBTP.setText("Bảo trì thông tin phòng máy");
        tvBTP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvBTPMouseClicked(evt);
            }
        });

        tvLS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tvLS.setText("Xem lịch sử hệ thống");
        tvLS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvLSMouseClicked(evt);
            }
        });

        tvLogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tvLogout.setText("Đăng xuất");

        taYCDK.setEditable(false);
        taYCDK.setColumns(20);
        taYCDK.setRows(5);
        jScrollPane2.setViewportView(taYCDK);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tvQuanLy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tvQLYC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tvQLTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tvYCDK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(tvYCTD, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, Short.MAX_VALUE)))))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tvBaoTri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tvBTL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tvBTP, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))))
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addComponent(tvLS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tvLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tvQuanLy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvQLYC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvYCDK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvYCTD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvQLTK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvBaoTri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvBTL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvBTP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvLS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Quản lý menu
    private void tvQuanLyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvQuanLyMouseClicked
        setDefaultColor();
        hideAll();
        tvQLYC.setVisible(true);
        tvQLTK.setVisible(true);
        tvQuanLy.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_tvQuanLyMouseClicked

    private void tvBaoTriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvBaoTriMouseClicked
        setDefaultColor();
        hideAll();
        tvBTL.setVisible(true);
        tvBTP.setVisible(true);
        tvBaoTri.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_tvBaoTriMouseClicked

    private void tvQLYCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvQLYCMouseClicked
        tvQuanLyMouseClicked(evt);
        tvYCTD.setVisible(true);
        tvYCDK.setVisible(true);
        setDefaultColor();
        tvQLYC.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_tvQLYCMouseClicked

    private void tvYCDKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvYCDKMouseClicked
        setDefaultColor();
        tvYCDK.setForeground(Color.MAGENTA);
        taYCDK.setVisible(true);
    }//GEN-LAST:event_tvYCDKMouseClicked

    static public void hideData(){
        taYCDK.setVisible(false);
    }
    
    private void tvYCTDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvYCTDMouseClicked
        setDefaultColor();
        tvYCTD.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_tvYCTDMouseClicked

    private void tvQLTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvQLTKMouseClicked
        tvQuanLyMouseClicked(evt);
        setDefaultColor();
        tvQLTK.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_tvQLTKMouseClicked

    private void tvBTLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvBTLMouseClicked
        tvBaoTriMouseClicked(evt);
        setDefaultColor();
        tvBTL.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_tvBTLMouseClicked

    private void tvBTPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvBTPMouseClicked
        tvBaoTriMouseClicked(evt);
        setDefaultColor();
        tvBTP.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_tvBTPMouseClicked

    private void tvLSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvLSMouseClicked
        hideAll();
        setDefaultColor();
        tvLS.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_tvLSMouseClicked

    
    static public void hideAll(){
        tvQLYC.setVisible(false);
        tvQLTK.setVisible(false);
        tvYCTD.setVisible(false);
        tvYCDK.setVisible(false);
        tvBTL.setVisible(false);
        tvBTP.setVisible(false);
    }
    
    static public void setDefaultColor(){
        tvQuanLy.setForeground(Color.black);
        tvLogout.setForeground(Color.black);
        tvBaoTri.setForeground(Color.black);
        tvLS.setForeground(Color.black);
        tvQLYC.setForeground(Color.black);
        tvQLTK.setForeground(Color.black);
        tvYCTD.setForeground(Color.black);
        tvYCDK.setForeground(Color.black);
        tvBTL.setForeground(Color.black);
        tvBTP.setForeground(Color.black);
    }
    
    //end of quản lý menu
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAdministrator().setVisible(true);
                onCreate();
                hideAll();
                setDefaultColor();
                hideData();
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTextArea taYCDK;
    private static javax.swing.JLabel tvBTL;
    private static javax.swing.JLabel tvBTP;
    private static javax.swing.JLabel tvBaoTri;
    private static javax.swing.JLabel tvLS;
    private static javax.swing.JLabel tvLogout;
    private static javax.swing.JLabel tvQLTK;
    private static javax.swing.JLabel tvQLYC;
    private static javax.swing.JLabel tvQuanLy;
    private static javax.swing.JLabel tvYCDK;
    private static javax.swing.JLabel tvYCTD;
    public static javax.swing.JLabel txtUser;
    // End of variables declaration//GEN-END:variables
}
